---
- name: Install Prometheus, Grafana, and Docker
  hosts: all
  become: yes
  tasks:

    # ✅ Install Required Packages
    - name: Install dependencies
      apt:
        name:
          - curl
          - wget
          - software-properties-common
        state: present
        update_cache: yes

    # ✅ Install Docker
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # ✅ Install Prometheus
    - name: Get the latest Prometheus release version
      shell: curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep "tag_name" | cut -d '"' -f 4 | sed 's/^v//'
      register: prometheus_version

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version.stdout }}/prometheus-{{ prometheus_version.stdout }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /tmp/prometheus-{{ prometheus_version.stdout }}.linux-amd64/prometheus /usr/local/bin/
    
    - name: Move Prometheus config
      command: mv /tmp/prometheus-{{ prometheus_version.stdout }}.linux-amd64/promtool /usr/local/bin/

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target
          [Service]
          User=root
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Prometheus
      systemd:
        daemon_reload: yes
        name: prometheus
        state: started
        enabled: yes

    # ✅ Install Grafana
    - name: Add Grafana repository key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes
